const foodlist=[
    {
       id:"1",
       image:"../../asset/food/cp1.jpg",
       name:"水饺",
       price:"￥2",
       count:0,
       Isdisplay:false

    },
    {
        id:"2",
        image:"../../asset/food/2.png",
        name:"面条",
        price:"￥8",
        count:0,
        Isdisplay:false
    },
    {
        id:"3",
        image:"../../asset/food/cp1.jpg",
        name:"包子",
        price:"￥1.5",
        count:0,
        Isdisplay:false
    },
    {
        id:"4",
        image:"../../asset/food/cp1.jpg",
        name:"米饭",
        price:"￥2",
        count:0,
        Isdisplay:false
    },
    {
        id:"5",
        image:"../../asset/food/cp1.jpg",
        name:"紫米粥",
        price:"￥5",
        count:0,
        Isdisplay:false
    },
    {
        id:"6",
        image:"../../asset/food/cp1.jpg",
        name:"披萨",
        price:"￥20",
        count:0,
        Isdisplay:false
    },
    {
        id:"7",
        image:"../../asset/food/cp1.jpg",
        name:"馒头",
        price:"￥1",
        count:0,
        Isdisplay:false
    },
    {
        id:"8",
        image:"../../asset/food/cp1.jpg",
        name:"油条",
        price:"￥2",
        count:0,
        Isdisplay:false
    },
    {
        id:"9",
        image:"../../asset/food/cp1.jpg",
        name:"煎饺",
        price:"￥4",
        count:0,
        Isdisplay:false
    },
    {
        id:"10",
        image:"../../asset/food/cp1.jpg",
        name:"豆浆",
        price:"￥2",
        count:0,
        Isdisplay:false
    },
    {
        id:"11",
        image:"../../asset/food/cp1.jpg",
        name:"牛奶",
        price:"￥5",
        count:0,
        Isdisplay:false
    },
    {
        id:"12",
        image:"../../asset/food/cp1.jpg",
        name:"酱香饼",
        price:"￥6",
        count:0,
        Isdisplay:false
    },
]

export default foodlist